name: Deploy to Vercel
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4

      - name: Testing
        run: echo "Test"
